### ISSUE TITLE
Error registering metrics AppDynamics v4.4

### ISSUE THREAD

**Issue by technoma-rodolfoarce** [Appdynamics/memcached-monitoring-extension#1]
I'm trying to run the memcached extension with AppDynamics v4.4 and Machine Agent 4.4.

I get the following error in the Machine agent:

> [AD Thread-Metric Reporter0] 20 Dec 2017 15:39:52,761  WARN ManagedMonitorDelegate - Error in registering following metrics with controller 
>[AD Thread-Metric Reporter0] 20 Dec 2017 15:39:52,762  WARN ManagedMonitorDelegate - Memcached||Metrics Collection Successful

On the AppDynamics controller I have the following error:

>[#|2017-12-20T15:40:22.209-0300|SEVERE|glassfish 4.1|com.appdynamics.METRICS.WRITE|_ThreadID=47;_ThreadName=http-listener-1(5);_TimeMillis=1513795222209;_LevelValue=1000;|Metric name "Memcached||curr_items" for app 3, returning metric id -2, unknown application error
com.singularity.ee.controller.api.exceptions.IllegalObjectStateException: Metric name Memcached||curr_items cannot contain consecutive : or |
>..

I noticed the double pipe(||) in "Memcached||curr_items"If I change the prefix, it still includes the "||" Metric path separator

**Comment by technoma-rodolfoarce** [comment]
#2

**Comment by venkatakonala** [comment]
Hi,

Can you please open a ticket with AppDynamics Support for getting your issue solved in an organised way? Please see the step 9 in "https://community.appdynamics.com/t5/Knowledge-Base/How-to-troubleshoot-missing-custom-metrics-or-extensions-metrics/ta-p/28695" to find the details about contacting support.

Thanks.

**Comment by venkatakonala** [comment]
Hi,

We have fixed this issue and released a new version. Please check the AppDynamics exchange for the latest version of the Memcached extension.

Thanks.
